### ISSUE TITLE
Help, please~

### ISSUE THREAD

**Issue by zzz1211** [biopto/EWALD#1]
I downloaded the Sinogram_03_hacat_03 as requested, but when I ran RecGTVIC.m, it didn't work。
<img width="618" alt="1710048075082" src="https://github.com/biopto/EWALD/assets/162860245/cbd36ef1-fed8-4550-b065-fae0a8f44599">

thank u！

**Comment by WKrauze** [comment]
Hi!
Could you please translate the error message to English?
Best,
Wojciech
